### ISSUE TITLE
Storywise image is not compatible with ARM cpu. 

### ISSUE THREAD

**Issue by EkielZan** [dotmethodme/storywise#2]
Storywise image is not compatible with ARM cpu. 

As a solution, I've clone the repo and change the dockerfile with a new 'FROM' clause:

FROM arm64v8/node:18-alpine3.18

Maybe changing the dockerfile to get the FROM with a build arg (with the default as "FROM node:18-alpine3.18")

**Comment by MihaiNueleanu** [comment]
I've added a multi-arch build pipeline, which should take care of this:
https://github.com/dotmethodme/storywise/commit/abc70470d760f52eb29637ec8b9f42f9dd810077

And the resulting image:
https://hub.docker.com/layers/mihainueleanu/storywise/0.18.1/images/sha256-857c725425764f6f626a39f7cee1cfa84234235bcf87ec768b5e9f32109ffc5b?context=repo


Could you check whether the new image works for your homelab? Did I get the right architectures? I'll add new ones when needed
